services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=${DATABASE_URL}
      - AGROMONITORING_API_KEY=${AGROMONITORING_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    restart: always